import type { Project } from "@/lib/types"

export const projects: Project[] = [
  {
    id: "1",
    title: "Condominium Ranch Extension",
    description: "Construction of a condominium ranch with modern and sustainable architecture.",
    image: "/images/ampliacion_rancho/1-6.webp?height=300&width=400&text=Residencial+Los+Pinos",
    gallery: [
      "/images/ampliacion_rancho/1-2.webp?height=400&width=600&text=de lado",
      "/images/ampliacion_rancho/1-3.webp?height=400&width=600&text=exterior",
      "/images/ampliacion_rancho/1-4.webp?height=400&width=600&text=atras",
      "/images/ampliacion_rancho/1-5.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-6.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-7.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-8.webp?height=400&width=600&text=2",
      "/images/ampliacion_rancho/1-1.webp?height=400&width=600&text=2",
    ],
    category: "Residential",
    location: "North Zone, City",
    area: "15,000 m²",
    year: "2025",
    client: "Norte Real Estate S.A.",
    duration: "18 months",
    features: [
      "50 residential units",
      "Green areas and parks",
      "Gym and pool",
      "24/7 security",
      "Underground parking",
    ],
  },

  {
    id: "2",
    title: "Plaza Central Shopping Center",
    description: "Modern shopping center with over 100 commercial stores, cinemas and food court.",
    image: "/placeholder.svg?height=300&width=400&text=Centro+Comercial+Plaza",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Fachada",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Interior",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Cines",
      "/placeholder.svg?height=400&width=600&text=Plaza+Central+Food+Court",
    ],
    category: "Commercial",
    location: "Downtown, City",
    area: "25,000 m²",
    year: "2022",
    client: "Central Commercial Group",
    duration: "24 months",
    features: [
      "100+ commercial stores",
      "Cinema complex",
      "Food court",
      "Parking for 500 vehicles",
      "Central air conditioning system",
    ],
  },
  {
    id: "3",
    title: "Skyline Corporate Tower",
    description: "20-story office building with cutting-edge technology and LEED certification.",
    image: "/placeholder.svg?height=300&width=400&text=Torre+Corporativa",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Exterior",
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Lobby",
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Oficinas",
      "/placeholder.svg?height=400&width=600&text=Torre+Skyline+Vista",
    ],
    category: "Corporate",
    location: "Financial District",
    area: "30,000 m²",
    year: "2023",
    client: "Skyline Corporation",
    duration: "30 months",
    features: [
      "20 office floors",
      "LEED Gold certification",
      "Smart automation system",
      "Rooftop helipad",
      "Conference center",
    ],
  },
  {
    id: "4",
    title: "Green Eco-Residential",
    description: "Sustainable development with 80 ecological houses and renewable energy systems.",
    image: "/placeholder.svg?height=300&width=400&text=Habitacional+Verde",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Verde+Casas+Solares",
      "/placeholder.svg?height=400&width=600&text=Verde+Jardines",
      "/placeholder.svg?height=400&width=600&text=Verde+Interior+Casa",
      "/placeholder.svg?height=400&width=600&text=Verde+Paneles+Solares",
    ],
    category: "Residential",
    location: "South Zone, City",
    area: "12,000 m²",
    year: "2024",
    client: "EcoVivir Developments",
    duration: "15 months",
    features: [
      "80 ecological houses",
      "Solar panels",
      "Water collection system",
      "Community gardens",
      "Electric charging station",
    ],
  },
  {
    id: "5",
    title: "San José Regional Hospital",
    description: "Modern hospital with 200 beds, state-of-the-art operating rooms and emergency area.",
    image: "/placeholder.svg?height=300&width=400&text=Hospital+Regional",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Hospital+Fachada",
      "/placeholder.svg?height=400&width=600&text=Hospital+Quirofanos",
      "/placeholder.svg?height=400&width=600&text=Hospital+Emergencias",
      "/placeholder.svg?height=400&width=600&text=Hospital+Habitaciones",
    ],
    category: "Health",
    location: "San José Downtown",
    area: "18,000 m²",
    year: "2022",
    client: "Ministry of Health",
    duration: "36 months",
    features: [
      "200 hospital beds",
      "8 modern operating rooms",
      "24/7 emergency area",
      "Clinical laboratory",
      "Emergency helipad",
    ],
  },
  {
    id: "6",
    title: "San José Educational Complex",
    description: "Educational campus with smart classrooms, laboratories and sports facilities.",
    image: "/placeholder.svg?height=400&width=600&text=Complejo+Educativo",
    gallery: [
      "/placeholder.svg?height=400&width=600&text=Educativo+Campus",
      "/placeholder.svg?height=400&width=600&text=Educativo+Aulas",
      "/placeholder.svg?height=400&width=600&text=Educativo+Laboratorios",
      "/placeholder.svg?height=400&width=600&text=Educativo+Deportes",
    ],
    category: "Educational",
    location: "East Zone, City",
    area: "8,000 m²",
    year: "2023",
    client: "San José Educational Foundation",
    duration: "20 months",
    features: [
      "30 smart classrooms",
      "Science laboratories",
      "Modern library",
      "Sports complex",
      "500-person auditorium",
    ],
  },
]

